<?php
// *** This file is generated by WebsiteBaker CE v1.2.0-alpha.1
// *** Creation date: 2016-04-02T23:11:07+00:00
// *** Do not modify this file manually
// *** WBCE will rebuild this file from time to time!!
// *************************************************
	$page_id    = 22;
	require('../../../../index.php');
// *************************************************
