<?php
// *** This file is generated by WebsiteBaker CE v1.2.0-alpha.1
// *** Creation date: 2016-04-02T22:44:57+00:00
// *** Do not modify this file manually
// *** WBCE will rebuild this file from time to time!!
// *************************************************
	$page_id    = 20;
	require('../../index.php');
// *************************************************
